import { FighterId, FighterStats } from './types';

/** Muted print-style palettes — flat cel colors that sit on painted stages.
 *  Primaries are spaced around the hue wheel so fighters read apart at a glance. */
export const FIGHTERS: Record<FighterId, FighterStats> = {
  zephyr: {
    id: 'zephyr',
    name: 'James',
    tagline: 'Sovereign of the Skies',
    color: '#2490c8',
    secondaryColor: '#d4a84a',
    glowColor: 'rgba(36, 144, 200, 0.35)',
    weight: 0.82,
    walkSpeed: 6.2,
    sprintSpeed: 9.6,
    jumpForce: 14.8,
    doubleJumps: 3, // Quadruple jump / 3 air wing flaps!
    punchDamage: 7,
    kickDamage: 13,
    throwDamage: 11,
    description: 'Winged avian dragon capable of true aerial flight, gliding gracefully on thermal drafts.',
    specialAbility: {
      name: 'Sky Glide & Gale Gust',
      badge: 'Wing Flight & Hover',
      description: 'Hold Jump in mid-air to spread wings and glide horizontally with near-zero gravity. Forward kicks unleash a gale wind shockwave.',
      icon: 'Feather',
    },
    superMove: {
      name: 'Tempest Dive',
      description: 'Soar skyward, then dive as a cyclone that vacuums foes inward and launches them with a gale shockwave.',
    },
    accessories: ['Animated Dragon Wings', 'Plumed Head Crest', 'Wind Tail Feather'],
  },
  brawler: {
    id: 'brawler',
    name: 'Andrew',
    tagline: 'The Flame Champion',
    color: '#d4452a',
    secondaryColor: '#e89040',
    glowColor: 'rgba(212, 69, 42, 0.35)',
    weight: 1.0,
    walkSpeed: 5.5,
    sprintSpeed: 8.8,
    jumpForce: 13.8,
    doubleJumps: 1,
    punchDamage: 8,
    kickDamage: 14,
    throwDamage: 12,
    description: 'Ferocious fire martial beast whose strikes ignite foes and dive-stomps explode in pillars of flame.',
    specialAbility: {
      name: 'Flame Burst & Burn',
      badge: 'Ignite & Meteor Stomp',
      description: 'Attacks ignite targets in lingering flame damage. Mid-air down-kicks dive at supersonic speed into an explosive fire blast.',
      icon: 'Flame',
    },
    superMove: {
      name: 'Inferno Meteor',
      description: 'Become a fireball, crash into the stage, and detonate a wide burn blast that leaves lingering magma.',
    },
    accessories: ['Flame Horns', 'Fluttering Headband Tails', 'Spiked Magma Pauldron', 'Flame Wrist Wraps'],
  },
  yeti: {
    id: 'yeti',
    name: 'Julian',
    tagline: 'The Frost Colossus',
    color: '#a8c4d4',
    secondaryColor: '#f0f6fa',
    glowColor: 'rgba(168, 196, 212, 0.4)',
    weight: 1.28,
    walkSpeed: 4.8,
    sprintSpeed: 7.6,
    jumpForce: 13.2,
    doubleJumps: 1,
    punchDamage: 10,
    kickDamage: 17,
    throwDamage: 15,
    description: 'Frozen behemoth with jagged crystalline ice spines that freezes enemies in their tracks.',
    specialAbility: {
      name: 'Frostbite Chill & Ice Spikes',
      badge: 'Freeze Slow & Glacial Spikes',
      description: 'Strikes inflict Frostbite, reducing enemy speed by 40% with chilling ice mist. Down attacks erupt sharp ice spikes from the platform.',
      icon: 'Snowflake',
    },
    superMove: {
      name: 'Glacial Lock',
      description: 'Slam the ground and freeze the nearest foe solid for a short hard-stun — a full stop, not just a slow.',
    },
    accessories: ['3 Back Ice Crystals', 'Frosted Crown Horns', 'Ice Boulder Gauntlets'],
  },
  striker: {
    id: 'striker',
    name: 'Bodhi',
    tagline: 'High Voltage Speedster',
    color: '#28b86a',
    secondaryColor: '#f0d040',
    glowColor: 'rgba(40, 184, 106, 0.35)',
    weight: 0.88,
    walkSpeed: 6.8,
    sprintSpeed: 10.5,
    jumpForce: 14.5,
    doubleJumps: 1,
    punchDamage: 6,
    kickDamage: 16,
    throwDamage: 10,
    description: 'Cybernetic speedster with jet boosters that harnesses static momentum into paralyzing lightning strikes.',
    specialAbility: {
      name: 'Static Overdrive',
      badge: 'Thunderbolt Shock Stun',
      description: 'Sprinting builds up 100% static electricity. When charged, your next strike unleashes a paralyzing chain lightning bolt with bonus hitstun.',
      icon: 'Zap',
    },
    superMove: {
      name: 'Thunder Rail',
      description: 'Instant lightning dash across the stage — hits everyone on the path and leaves them shocked.',
    },
    accessories: ['Twin Lightning Antennae', 'Jet Thruster Exhaust Pack', 'Holo Cyber Visor'],
  },
  titan: {
    id: 'titan',
    name: 'Felix',
    tagline: 'Unstoppable Colossus',
    color: '#d4a820',
    secondaryColor: '#8a5a28',
    glowColor: 'rgba(212, 168, 32, 0.35)',
    weight: 1.35,
    walkSpeed: 4.6,
    sprintSpeed: 7.2,
    jumpForce: 13.0,
    doubleJumps: 1,
    punchDamage: 11,
    kickDamage: 18,
    throwDamage: 17,
    description: 'Armored minotaur juggernaut with unbreakable super armor poise and seismic ground-shattering stomps.',
    specialAbility: {
      name: 'Colossus Super Armor',
      badge: 'Super Armor & Quake Tremor',
      description: 'Immune to flinching during heavy attacks. Downward stomps and throws cause a seismic shockwave across the entire platform.',
      icon: 'Shield',
    },
    superMove: {
      name: 'Titan Crush',
      description: 'Super-armor charge that grabs and spikes the first fighter hit into the platform with a massive quake.',
    },
    accessories: ['Golden Minotaur Horns', 'Spiked Gladiator Pauldrons', 'Runic Core Reactor'],
  },
  shinobi: {
    id: 'shinobi',
    name: 'Maui',
    tagline: 'The Void Ninja',
    color: '#6b3aad',
    secondaryColor: '#c45a78',
    glowColor: 'rgba(107, 58, 173, 0.35)',
    weight: 0.92,
    walkSpeed: 6.0,
    sprintSpeed: 9.4,
    jumpForce: 14.0,
    doubleJumps: 2, // Triple jump!
    punchDamage: 7,
    kickDamage: 13,
    throwDamage: 14,
    description: 'Acrobatic shadow assassin sporting a flowing scarf that phases through foes and lands lethal backstabs.',
    specialAbility: {
      name: 'Shadow Phase & Backstab',
      badge: 'Intangible Dash & Criticals',
      description: 'Sprinting phases into intangible shadow smoke passing through opponents. Striking enemies from behind deals +35% critical launch force.',
      icon: 'Eye',
    },
    superMove: {
      name: 'Void Ambush',
      description: 'Vanish, reappear behind the nearest enemy, and land a guaranteed backstab critical.',
    },
    accessories: ['Flowing Dual-Tail Scarf', 'Forehead Ninja Crest', 'Kitsune Ears', 'Twin Kunai Holster'],
  },
  monk: {
    id: 'monk',
    name: 'Aaron',
    tagline: 'Drunken Monkey Sage',
    color: '#8f5a28',
    secondaryColor: '#5a8a38',
    glowColor: 'rgba(143, 90, 40, 0.35)',
    weight: 0.95,
    walkSpeed: 5.8,
    sprintSpeed: 9.0,
    jumpForce: 14.2,
    doubleJumps: 2,
    punchDamage: 8,
    kickDamage: 15,
    throwDamage: 13,
    description:
      'Tipsy monkey martial artist who stumbles with deceptive grace, building sway into a spinning monkey flurry.',
    specialAbility: {
      name: 'Drunken Sway & Monkey Spin',
      badge: 'Tipsy Charge & Stumble',
      description:
        'Moving builds Tipsy Charge. At full charge, your next hit unleashes a spinning Monkey Flurry with bonus launch and leaves foes stumbling. High sway also softens incoming knockback.',
      icon: 'Wine',
    },
    superMove: {
      name: 'Drunken Whirlwind',
      description: 'Uncontrolled spinning flurry that hits multiple times, tipsifies everyone nearby, and softens your own knockback.',
    },
    accessories: ['Round Top Ears', 'Curled Tail', 'Muzzle', 'Leaf Belt'],
  },
  lotus: {
    id: 'lotus',
    name: 'Lyla',
    tagline: 'Lightning Leg Legend',
    color: '#c05088',
    secondaryColor: '#4050b0',
    glowColor: 'rgba(192, 80, 136, 0.35)',
    weight: 0.9,
    walkSpeed: 6.4,
    sprintSpeed: 9.8,
    jumpForce: 14.4,
    doubleJumps: 2,
    punchDamage: 6,
    kickDamage: 17,
    throwDamage: 12,
    description:
      'Graceful kick specialist whose lightning-fast legs chain into a blistering multi-hit flurry.',
    specialAbility: {
      name: 'Lightning Kick Barrage',
      badge: 'Multi-Hit Kick Storm',
      description:
        'Kicks start faster and stay active longer, landing repeated lightning strikes. Each follow-up hit chips extra damage and stuns briefly.',
      icon: 'Sparkles',
    },
    superMove: {
      name: 'Thousand Lotus Kicks',
      description: 'Screen-locking kick storm: many lightning kick hits that end in a rising finisher launch.',
    },
    accessories: ['Twin Hair Buns', 'Spiked Wrist Cuffs', 'Qipao Skirt Flaps', 'Ankle Ribbons'],
  },
};
