import { FighterId, FighterStats } from './types';

export const FIGHTERS: Record<FighterId, FighterStats> = {
  zephyr: {
    id: 'zephyr',
    name: 'Zephyr Drake',
    tagline: 'Sovereign of the Skies',
    color: '#0ea5e9',
    secondaryColor: '#38bdf8',
    glowColor: 'rgba(14, 165, 233, 0.45)',
    weight: 0.82,
    walkSpeed: 6.2,
    sprintSpeed: 9.6,
    jumpForce: 14.8,
    doubleJumps: 3, // Quadruple jump / 3 air wing flaps!
    punchDamage: 7,
    kickDamage: 13,
    throwDamage: 11,
    description: 'Winged avian dragon capable of true aerial flight, gliding gracefully on thermal drafts.',
    specialAbility: {
      name: 'Sky Glide & Gale Gust',
      badge: 'Wing Flight & Hover',
      description: 'Hold Jump in mid-air to spread wings and glide horizontally with near-zero gravity. Forward kicks unleash a gale wind shockwave.',
      icon: 'Feather',
    },
    accessories: ['Animated Dragon Wings', 'Plumed Head Crest', 'Wind Tail Feather'],
  },
  brawler: {
    id: 'brawler',
    name: 'Blaze Brawler',
    tagline: 'The Flame Champion',
    color: '#ef4444',
    secondaryColor: '#f97316',
    glowColor: 'rgba(239, 68, 68, 0.45)',
    weight: 1.0,
    walkSpeed: 5.5,
    sprintSpeed: 8.8,
    jumpForce: 13.8,
    doubleJumps: 1,
    punchDamage: 8,
    kickDamage: 14,
    throwDamage: 12,
    description: 'Ferocious fire martial beast whose strikes ignite foes and dive-stomps explode in pillars of flame.',
    specialAbility: {
      name: 'Flame Burst & Burn',
      badge: 'Ignite & Meteor Stomp',
      description: 'Attacks ignite targets in lingering flame damage. Mid-air down-kicks dive at supersonic speed into an explosive fire blast.',
      icon: 'Flame',
    },
    accessories: ['Flame Horns', 'Fluttering Headband Tails', 'Spiked Magma Pauldron', 'Flame Wrist Wraps'],
  },
  yeti: {
    id: 'yeti',
    name: 'Glacial Yeti',
    tagline: 'The Frost Colossus',
    color: '#0284c7',
    secondaryColor: '#e0f2fe',
    glowColor: 'rgba(56, 189, 248, 0.5)',
    weight: 1.28,
    walkSpeed: 4.8,
    sprintSpeed: 7.6,
    jumpForce: 13.2,
    doubleJumps: 1,
    punchDamage: 10,
    kickDamage: 17,
    throwDamage: 15,
    description: 'Frozen behemoth with jagged crystalline ice spines that freezes enemies in their tracks.',
    specialAbility: {
      name: 'Frostbite Chill & Ice Spikes',
      badge: 'Freeze Slow & Glacial Spikes',
      description: 'Strikes inflict Frostbite, reducing enemy speed by 40% with chilling ice mist. Down attacks erupt sharp ice spikes from the platform.',
      icon: 'Snowflake',
    },
    accessories: ['3 Back Ice Crystals', 'Frosted Crown Horns', 'Ice Boulder Gauntlets'],
  },
  striker: {
    id: 'striker',
    name: 'Neon Striker',
    tagline: 'High Voltage Speedster',
    color: '#06b6d4',
    secondaryColor: '#3b82f6',
    glowColor: 'rgba(6, 182, 212, 0.45)',
    weight: 0.88,
    walkSpeed: 6.8,
    sprintSpeed: 10.5,
    jumpForce: 14.5,
    doubleJumps: 1,
    punchDamage: 6,
    kickDamage: 16,
    throwDamage: 10,
    description: 'Cybernetic speedster with jet boosters that harnesses static momentum into paralyzing lightning strikes.',
    specialAbility: {
      name: 'Static Overdrive',
      badge: 'Thunderbolt Shock Stun',
      description: 'Sprinting builds up 100% static electricity. When charged, your next strike unleashes a paralyzing chain lightning bolt with bonus hitstun.',
      icon: 'Zap',
    },
    accessories: ['Twin Lightning Antennae', 'Jet Thruster Exhaust Pack', 'Holo Cyber Visor'],
  },
  titan: {
    id: 'titan',
    name: 'Gilded Titan',
    tagline: 'Unstoppable Colossus',
    color: '#eab308',
    secondaryColor: '#d97706',
    glowColor: 'rgba(234, 179, 8, 0.45)',
    weight: 1.35,
    walkSpeed: 4.6,
    sprintSpeed: 7.2,
    jumpForce: 13.0,
    doubleJumps: 1,
    punchDamage: 11,
    kickDamage: 18,
    throwDamage: 17,
    description: 'Armored minotaur juggernaut with unbreakable super armor poise and seismic ground-shattering stomps.',
    specialAbility: {
      name: 'Colossus Super Armor',
      badge: 'Super Armor & Quake Tremor',
      description: 'Immune to flinching during heavy attacks. Downward stomps and throws cause a seismic shockwave across the entire platform.',
      icon: 'Shield',
    },
    accessories: ['Golden Minotaur Horns', 'Spiked Gladiator Pauldrons', 'Runic Core Reactor'],
  },
  shinobi: {
    id: 'shinobi',
    name: 'Shadow Shinobi',
    tagline: 'The Void Ninja',
    color: '#a855f7',
    secondaryColor: '#ec4899',
    glowColor: 'rgba(168, 85, 247, 0.45)',
    weight: 0.92,
    walkSpeed: 6.0,
    sprintSpeed: 9.4,
    jumpForce: 14.0,
    doubleJumps: 2, // Triple jump!
    punchDamage: 7,
    kickDamage: 13,
    throwDamage: 14,
    description: 'Acrobatic shadow assassin sporting a flowing scarf that phases through foes and lands lethal backstabs.',
    specialAbility: {
      name: 'Shadow Phase & Backstab',
      badge: 'Intangible Dash & Criticals',
      description: 'Sprinting phases into intangible shadow smoke passing through opponents. Striking enemies from behind deals +35% critical launch force.',
      icon: 'Eye',
    },
    accessories: ['Flowing Dual-Tail Scarf', 'Forehead Ninja Crest', 'Kitsune Ears', 'Twin Kunai Holster'],
  },
};

